import ProjectDescription
import ProjectDescriptionHelpers

let workspace = Workspace(
    name: "Souzip",
    projects: [
        "Projects/**",
    ],
    schemes: DefaultSchemes.workspaceTestScheme(),
    generationOptions: .options(
        autogeneratedWorkspaceSchemes: .disabled
    )
)
